[loggers]
keys=root,uvicorn,uvicorn_error,uvicorn_access

[handlers]
keys=default,access

[formatters]
keys=json,access

[logger_root]
level=INFO
handlers=default

[logger_uvicorn]
level=INFO
handlers=default
propagate=0
qualname=uvicorn

[logger_uvicorn_error]
level=INFO
handlers=default
propagate=0
qualname=uvicorn.error

[logger_uvicorn_access]
level=INFO
handlers=access
propagate=0
qualname=uvicorn.access

[handler_default]
class=StreamHandler
formatter=json
args=(sys.stdout,)

[handler_access]
class=StreamHandler
formatter=access
args=(sys.stdout,)

[formatter_json]
format={"time":"%(asctime)s","level":"%(levelname)s","logger":"%(name)s","message":"%(message)s"}

[formatter_access]
format={"time":"%(asctime)s","level":"%(levelname)s","logger":"%(name)s","message":"%(message)s"}

