listen_addresses = '*'
port = 5432
max_connections = 150
shared_buffers = 256MB
effective_cache_size = 768MB
maintenance_work_mem = 64MB
work_mem = 8MB
wal_level = replica
log_min_duration_statement = 1000
timezone = 'UTC'

